# Generated by Django 5.1.3 on 2024-11-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='Item_name',
        ),
        migrations.RemoveField(
            model_name='items',
            name='Price',
        ),
        migrations.RemoveField(
            model_name='items',
            name='description',
        ),
        migrations.AddField(
            model_name='feedback',
            name='Image',
            field=models.ImageField(blank=True, upload_to='Items/'),
        ),
    ]
