# Generated by Django 5.1.3 on 2024-11-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0004_remove_feedback_image_items_item_name_items_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktable',
            name='Booking_date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
